apiVersion: batch/v1
kind: Job
metadata:
  name: {{job_name}}
spec:
  template:
    spec:
      containers:
      - name: {{job_name}}
        image: gcr.io/serene-radius-314018/python/python-base:0.0.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: ["./run.sh {{gcs_path}} '{{run_command}}'"]
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "500m"
      restartPolicy: Never
  backoffLimit: 1