apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-scheduler
  labels:
    app: job-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-scheduler
  template:
    metadata:
      labels:
        app: job-scheduler
    spec:
      serviceAccountName: k8s-admin
      containers:
      - name: job-scheduler
        image: gcr.io/serene-radius-314018/job-scheduler/job-scheduler:0.0.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: EXAMPLE
          value: VALUE
---
apiVersion: v1
kind: Service
metadata:
  name: job-scheduler
spec:
  selector: 
    app: job-scheduler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
